version: '3'
services:
    rediSearch_v2:
        image: redislabs/redisearch
        container_name: redisearch-shopdev
        ports:
            - '6379:6379'
        networks:
            - server-shopdev-network

    server-api-shopdev:
        image: server-shopdev
        ports:
            - '8080:8080'
        build:
            context: .
        container_name: server-shopdev-api
        networks:
            - server-shopdev-network
        depends_on:
            - rediSearch_v2

networks:
    server-shopdev-network:
        driver: bridge
