version: '3'
services:
    redis-img:
        image: redis/redis-stack-server
        container_name: redis_shopdev
        ports:
            - '6379:6379'
        networks:
            - server-shopdev-network

    server-shopdev-be:
        build:
            context: .
        ports:
            - '8080:8080'
        container_name: server-shopdev-api
        networks:
            - server-shopdev-network


networks:
    server-shopdev-network:
        driver: bridge
