
@baseUrl = http://localhost:8080
@authRoute = /api/v1/auth


###
POST {{baseUrl}}{{authRoute}}/login
Content-Type: application/json

{
    "email" : "fadewalker4440@gmail.com",
    "password" : "A123456xyZ"
}
###
POST {{baseUrl}}{{authRoute}}/register
Content-Type: application/json

{
    "email" : "hoanghieuss3344@gmail.com",
    "password" : "A123456xyZ"
}

###
POST {{baseUrl}}{{authRoute}}/register
Content-Type: application/json

{
    "email" : "fadewalker4440@gmail.com",
    "password" : "A123456xyZ"
}


###
POST {{baseUrl}}{{authRoute}}/register
Content-Type: application/json

{
    "email" : "hongntph19500@fpt.edu.vn",
    "password" : "A123456xyZ"
}

###
GET {{baseUrl}}{{authRoute}}/activate?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjdhYjA5YjE4NzYxMzdjZTU5MmMwZjAiLCJpYXQiOjE3MTk1MDUxODEsImV4cCI6MTcyMDQwNTE4MX0.t-0_WVEOgCfRF4UaBHUo1xWssotd7Jqr8-JVnfXSEuw

###
GET {{baseUrl}}{{authRoute}}/logout

###
GET {{baseUrl}}{{authRoute}}/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjdhYjA5YjE4NzYxMzdjZTU5MmMwZjAiLCJpYXQiOjE3MTk1MDYyNzAsImV4cCI6MTcyMDQwNjI3MH0.jdkM5TmHVjas8T0eDSmFnU4Vy-504Kn4oHRj1-enf08

###
GET {{baseUrl}}{{authRoute}}/liked
Accept-Language: vn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YjA5ZDJiMGMzMGE1ODEwNGU1ODEiLCJpYXQiOjE3MDI2MjE2NjcsImV4cCI6MTcwMzUyMTY2N30.1m_xFAJhZPCW-3e5DctH0tzTIp2vxNaTAdBGd6DYDm0

###
POST {{baseUrl}}{{authRoute}}/liked/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YjA5ZDJiMGMzMGE1ODEwNGU1ODEiLCJpYXQiOjE3MDI2MjE2NjcsImV4cCI6MTcwMzUyMTY2N30.1m_xFAJhZPCW-3e5DctH0tzTIp2vxNaTAdBGd6DYDm0

{
    "productId" : "64f290e6e30792fe4c989455"
}
###
POST {{baseUrl}}{{authRoute}}/liked/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGU5YjA5ZDJiMGMzMGE1ODEwNGU1ODEiLCJpYXQiOjE3MDI2MjE2NjcsImV4cCI6MTcwMzUyMTY2N30.1m_xFAJhZPCW-3e5DctH0tzTIp2vxNaTAdBGd6DYDm0

{
    "productId" : "64f290e6e30792fe4c989455"
}


13.215.179.135
###
POST http://13.215.179.135:8080/api/v1/auth/login
Content-Type: application/json

{
    "email" : "fadewalker4440@gmail.com",
    "password" : "A123456xyZ"
}
###
GET {{baseUrl}}{{authRoute}}/redis

