# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI server-shopdev

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo ${{ secrets.ENV_FILE }}" >> .env

            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              run: docker build -t hieupc05/server-shopdev .
            - name: Publish image to docker hub
              run: docker push hieupc05/server-shopdev:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull hieupc05/server-shopdev:latest
            - name: Pull image rediSearch
              run: docker pull redislabs/redisearch
            - name: Delete old container
              run: docker rm -f server-shopdev-api redisearch-shopdev
            - name: Run redisearch
              run: docker run -d -p 6379:6379 -name redisearch-shopdev redislabs/redisearch
            - name: Run docker container
              run: docker run -d -p 8080:8080 -name server-shopdev-api hieupc05/server-shopdev
